"""Bearer-token authentication for the rgt-vault HTTP server.

The token is a random 32-byte value, urlsafe-base64-encoded (43 characters
plus padding). It is stored in a single file on disk; the file's contents
are the token. The file is created with restrictive permissions on POSIX
(``0o600``); on Windows, ``icacls`` is the closest equivalent but the
process identity already gates file access, so we only log a warning if
``os.chmod`` is a no-op.

The token store does not try to be a password manager. It is intentionally
minimal: one file, one token, no rotation primitives. To rotate, delete
the file and let ``load_or_create_token`` mint a new one on the next
``rgt-vault init`` or ``serve`` startup.

Audit integration: every authenticated request gets a short "token id"
(the first 8 hex chars of ``sha256(token)``) recorded in the audit log.
This lets the operator correlate HTTP activity with the hash-chained
audit log without ever recording the token itself.
"""

from __future__ import annotations

import hashlib
import os
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from rgt_vault.exceptions import ServerAuthError

DEFAULT_TOKEN_PATH = Path.home() / ".config" / "rgt-vault" / "server.token"


def generate_token() -> str:
    """Return a fresh urlsafe-base64-encoded 32-byte random token (43 chars)."""
    return secrets.token_urlsafe(32)


def _token_id(token: str) -> str:
    """Stable short identifier for a token, safe to record in audit logs."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()[:8]


@dataclass
class TokenStore:
    """File-backed bearer token store.

    The on-disk format is intentionally trivial: the file's contents are the
    token string (no JSON wrapper, no metadata). The token is 43 characters
    long when generated by :func:`generate_token`; we strip whitespace before
    comparison.
    """

    path: Path

    def __post_init__(self) -> None:
        self.path = Path(self.path)
        # Make sure the parent directory exists with restrictive perms before
        # we write the token file. We don't fail closed if chmod is a no-op
        # (e.g. on Windows or on a filesystem we don't own); the operator
        # should audit token-file permissions separately.
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if os.name == "posix":
            try:
                os.chmod(self.path.parent, 0o700)
            except OSError:
                pass

    def exists(self) -> bool:
        return self.path.is_file()

    def write(self, token: str) -> None:
        if not token:
            raise ServerAuthError("Refusing to write an empty token.")
        self.path.write_text(token.strip() + "\n", encoding="utf-8")
        if os.name == "posix":
            try:
                os.chmod(self.path, 0o600)
            except OSError:
                pass
        # On Windows, restrict via the inherited DACL; there's no POSIX-style
        # chmod. The process identity is the primary access gate.

    def read(self) -> str:
        if not self.path.is_file():
            raise ServerAuthError(
                f"Token file not found: {self.path}. Run `rgt-vault init` (or pass --token-file to a file that exists)."
            )
        return self.path.read_text(encoding="utf-8").strip()

    def id_for(self, token: str) -> str:
        return _token_id(token)

    def constant_time_compare(self, presented: str, stored: str) -> bool:
        """Compare two tokens in constant time to avoid timing side channels."""
        # secrets.compare_digest requires equal-length strings; if the lengths
        # differ, fall through to a False result without leaking length-based
        # timing on the equal-length branch.
        if len(presented) != len(stored):
            return False
        return secrets.compare_digest(presented, stored)

    def verify(self, presented: Optional[str]) -> str:
        """Return the token id if ``presented`` matches the stored token.

        Raises :class:`ServerAuthError` otherwise. The returned id is safe to
        log; the token itself is never logged.
        """
        if not presented:
            raise ServerAuthError("Missing Authorization header.")
        presented = presented.strip()
        # Accept both "Bearer <token>" and the raw token; the latter is
        # convenient for local-only clients.
        if presented.lower().startswith("bearer "):
            presented = presented[7:].strip()
        if not presented:
            raise ServerAuthError("Empty bearer token.")
        stored = self.read()
        if not self.constant_time_compare(presented, stored):
            raise ServerAuthError("Invalid bearer token.")
        return self.id_for(presented)


def load_or_create_token(path: Optional[Path] = None) -> tuple[Path, str]:
    """Return ``(path, token)``, creating the file with a fresh token if missing.

    If the file exists but is empty or unreadable, raise :class:`ServerAuthError`
    — the operator must decide whether to keep or delete the existing file.
    We never overwrite a non-empty file silently.
    """
    p = Path(path) if path else DEFAULT_TOKEN_PATH
    store = TokenStore(p)
    if store.exists():
        existing = store.read()
        if not existing:
            raise ServerAuthError(
                f"Token file {p} is empty. Delete it and rerun, or replace it with a non-empty token."
            )
        return p, existing
    token = generate_token()
    store.write(token)
    return p, token


__all__ = [
    "DEFAULT_TOKEN_PATH",
    "TokenStore",
    "generate_token",
    "load_or_create_token",
]
