// Package kdf implements the multi-stage key derivation used by rgt-vault.
//
// This is a port of rgt_vault/keychain.py (KeyDerivationOrchestrator,
// _argon2_id_kdf, _hkdf_expand). It produces a (KEK, nonce) pair from a
// master secret, a per-vault salt, and a binding context, suitable for
// wrapping data encryption keys (DEKs) with the package crypto.
//
// Pipeline (all stages are deterministic; no global state):
//
//	stage 1: Argon2id(stretch)
//	    master (any length) + salt (16 bytes) -> 32-byte intermediate
//	    parameters: memory_cost (KB), time_cost, parallelism
//	stage 2: HKDF-SHA512(bind)
//	    intermediate (32) + context -> 64-byte binding_material
//	stage 3: HKDF-SHA256(expand)
//	    binding_material[:32] = KEK (returned as-is)
//	    binding_material[32:]  -> HKDF-Expand(info="nonce expansion", L=12) = nonce
//
// Constants match the Python implementation. In particular, HKDF salt is
// None (zero-length) and the nonce-expansion info is the literal byte
// string "nonce expansion".
//
// Cross-language parity: see TestVectorFromPython. The hardcoded vector was
// generated by rgt_vault.keychain with small Argon2id parameters
// (memory=64MB, time=2, parallelism=2) so the test runs in well under a
// second on any modern machine.
package kdf

import (
	"crypto/subtle"
	"errors"
	"fmt"
	"io"

	"golang.org/x/crypto/argon2"
)

// Default parameters match rgt_vault/keychain.py defaults. These are heavy:
// ~256 MB of RAM and ~1 second of CPU per derive on a 2020-class machine.
// The Go port uses the same defaults so that keys derived on the Go line
// match keys derived on the Python line.
const (
	DefaultMemoryCost  uint32 = 262144 // 256 MB in KiB
	DefaultTimeCost    uint32 = 4
	DefaultParallelism uint8  = 4
)

// Sentinel errors. Match the convention in internal/crypto/crypto.go.
var (
	ErrInvalidSalt     = errors.New("kdf: salt must be at least 8 bytes")
	ErrInvalidContext  = errors.New("kdf: context must be non-empty")
	ErrInvalidParams   = errors.New("kdf: invalid Argon2id parameters")
	ErrDeriveFailed    = errors.New("kdf: derive failed")
)

// DerivedKeyMaterial is the (KEK, nonce) pair produced by Derive.
//
// KEK is a 32-byte AES-256 key, suitable for use with internal/crypto.Encrypt.
// Nonce is 12 bytes, suitable for AES-GCM. The two are returned together so
// that callers cannot accidentally mix them up (KEK from one vault with a
// nonce from another).
type DerivedKeyMaterial struct {
	Key   [32]byte
	Nonce [12]byte
}

// Params is the Argon2id cost parameter set. Zero values are invalid.
type Params struct {
	MemoryCost  uint32 // KB
	TimeCost    uint32
	Parallelism uint8
}

// DefaultParams returns the rgt_vault-default Argon2id parameters.
func DefaultParams() Params {
	return Params{
		MemoryCost:  DefaultMemoryCost,
		TimeCost:    DefaultTimeCost,
		Parallelism: DefaultParallelism,
	}
}

// Derive runs the full three-stage KDF and returns the (KEK, nonce) pair.
//
//	master   : arbitrary-length secret (typically 32 bytes, but any length is fine)
//	salt     : per-vault salt; MUST be at least 8 bytes
//	context  : binding context, e.g. "rgt-vault/vault-id/derive/v1"; non-empty
//	params   : Argon2id cost parameters; use DefaultParams() for production
//
// The output is deterministic for any (master, salt, context, params)
// tuple. Different (salt, context) pairs yield cryptographically
// independent outputs, even with the same master.
func Derive(master, salt, context []byte, params Params) (DerivedKeyMaterial, error) {
	if len(salt) < 8 {
		return DerivedKeyMaterial{}, ErrInvalidSalt
	}
	if len(context) == 0 {
		return DerivedKeyMaterial{}, ErrInvalidContext
	}
	if params.MemoryCost == 0 || params.TimeCost == 0 || params.Parallelism == 0 {
		return DerivedKeyMaterial{}, ErrInvalidParams
	}

	// Stage 1: Argon2id stretch.
	intermediate := argon2.IDKey(master, salt, params.TimeCost, params.MemoryCost, params.Parallelism, 32)

	// Stage 2: HKDF-SHA512 bind to context, produce 64 bytes.
	binding, err := hkdfExpand(intermediate, context, 64, sha512NewFunc)
	if err != nil {
		return DerivedKeyMaterial{}, fmt.Errorf("%w: stage 2: %v", ErrDeriveFailed, err)
	}
	if len(binding) != 64 {
		// Should be unreachable; defensive only.
		return DerivedKeyMaterial{}, fmt.Errorf("%w: stage 2 produced %d bytes, want 64", ErrDeriveFailed, len(binding))
	}

	// Stage 3: split, expand the second half into a 12-byte nonce.
	var kek [32]byte
	copy(kek[:], binding[:32])
	nonceRaw := binding[32:64]
	nonceBytes, err := hkdfExpand(nonceRaw, []byte("nonce expansion"), 12, sha256NewFunc)
	if err != nil {
		return DerivedKeyMaterial{}, fmt.Errorf("%w: stage 3: %v", ErrDeriveFailed, err)
	}
	if len(nonceBytes) != 12 {
		return DerivedKeyMaterial{}, fmt.Errorf("%w: stage 3 produced %d bytes, want 12", ErrDeriveFailed, len(nonceBytes))
	}
	var nonce [12]byte
	copy(nonce[:], nonceBytes)

	return DerivedKeyMaterial{Key: kek, Nonce: nonce}, nil
}

// Salt is a small helper that returns a cryptographically random salt of
// the given length, suitable for use as input to Derive. The default
// rgt-vault salt length is 16 bytes; use at least 8 (we enforce this in
// Derive). Exposed as a convenience so callers don't have to import
// crypto/rand directly.
func Salt(length int) ([]byte, error) {
	if length < 8 {
		return nil, ErrInvalidSalt
	}
	out := make([]byte, length)
	if _, err := randReader.Read(out); err != nil {
		return nil, fmt.Errorf("kdf: read random: %w", err)
	}
	return out, nil
}

// ConstantTimeEq is a helper for callers that want to compare a derived
// key against an expected value without leaking timing information.
// Exposed because it is not in the stdlib and the rest of the project
// will eventually need it.
func ConstantTimeEq(a, b []byte) bool {
	return subtle.ConstantTimeCompare(a, b) == 1
}

// randReader is the default entropy source for callers that need random
// bytes (e.g. for salts). Exposed so tests can swap it out.
var randReader io.Reader = cryptoRandReader
