package kdf

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"testing"
)

// Cross-language parity test vector.
//
// Generated by rgt_vault/keychain.py:
//   master = MasterSecret(8dee7421c4cf8b24cc335a05e5fad5266e5f9d2f5fc84e794509ae93226d9d9e)
//   salt   = 594000f029aaff03397b96bdd2f20e69
//   context = b"rgt-vault/go-kdf-v1"
//   params = {memory_cost: 65536, time_cost: 2, parallelism: 2}
//   output.kek   = 4bf8982e82da67876783e1862594cd2110f16dac78d7d9ec52245efa59f21295
//   output.nonce = c1da59aabbe8035ef9a6bb3b
//
// If this test fails, the Go KDF has drifted from the Python line. That's
// not a test failure to fix in Go: it is a wire-format break that
// invalidates every key ever derived on the Go line. Fix it before any
// data crosses the language boundary.
func TestVectorFromPython(t *testing.T) {
	master, _ := hex.DecodeString("8dee7421c4cf8b24cc335a05e5fad5266e5f9d2f5fc84e794509ae93226d9d9e")
	salt, _ := hex.DecodeString("594000f029aaff03397b96bdd2f20e69")
	context := []byte("rgt-vault/go-kdf-v1")
	wantKEK, _ := hex.DecodeString("4bf8982e82da67876783e1862594cd2110f16dac78d7d9ec52245efa59f21295")
	wantNonce, _ := hex.DecodeString("c1da59aabbe8035ef9a6bb3b")

	params := Params{MemoryCost: 65536, TimeCost: 2, Parallelism: 2}
	dm, err := Derive(master, salt, context, params)
	if err != nil {
		t.Fatalf("Derive failed: %v", err)
	}
	if !bytes.Equal(dm.Key[:], wantKEK) {
		t.Errorf("KEK mismatch:\n  got  %x\n  want %x", dm.Key[:], wantKEK)
	}
	if !bytes.Equal(dm.Nonce[:], wantNonce) {
		t.Errorf("Nonce mismatch:\n  got  %x\n  want %x", dm.Nonce[:], wantNonce)
	}
}

// TestDerive_OutputLengths ensures stage 1 -> 32, stage 2 -> 64, stage 3 ->
// 12 bytes, by inspecting the DerivedKeyMaterial struct.
func TestDerive_OutputLengths(t *testing.T) {
	master := make([]byte, 32)
	salt := make([]byte, 16)
	context := []byte("rgt-vault/test/lengths")
	if _, err := rand.Read(master); err != nil {
		t.Fatal(err)
	}
	if _, err := rand.Read(salt); err != nil {
		t.Fatal(err)
	}
	dm, err := Derive(master, salt, context, smallTestParams())
	if err != nil {
		t.Fatalf("Derive failed: %v", err)
	}
	if got := len(dm.Key); got != 32 {
		t.Errorf("Key length: got %d, want 32", got)
	}
	if got := len(dm.Nonce); got != 12 {
		t.Errorf("Nonce length: got %d, want 12", got)
	}
}

// TestDerive_Deterministic confirms that the same inputs produce the same
// outputs, every time. Catches non-determinism regressions (e.g. someone
// accidentally introduces rand.Read in the middle of a derive).
func TestDerive_Deterministic(t *testing.T) {
	master := bytes.Repeat([]byte{0xAA}, 32)
	salt := bytes.Repeat([]byte{0xBB}, 16)
	context := []byte("rgt-vault/test/determinism")

	dm1, err := Derive(master, salt, context, smallTestParams())
	if err != nil {
		t.Fatal(err)
	}
	dm2, err := Derive(master, salt, context, smallTestParams())
	if err != nil {
		t.Fatal(err)
	}
	if dm1 != dm2 {
		t.Errorf("Derive is non-deterministic:\n  run 1: %x %x\n  run 2: %x %x",
			dm1.Key[:], dm1.Nonce[:], dm2.Key[:], dm2.Nonce[:])
	}
}

// TestDerive_DifferentInputsDifferentOutputs is a sanity check that the
// three input parameters (master, salt, context) are all consumed. If
// any one is silently ignored, this test catches it.
func TestDerive_DifferentInputsDifferentOutputs(t *testing.T) {
	baseMaster := bytes.Repeat([]byte{0x11}, 32)
	baseSalt := bytes.Repeat([]byte{0x22}, 16)
	baseContext := []byte("rgt-vault/test/sensitivity")
	baseParams := smallTestParams()

	cases := []struct {
		name   string
		master []byte
		salt   []byte
		ctx    []byte
	}{
		{"master+1", append([]byte{0x12}, baseMaster[1:]...), baseSalt, baseContext},
		{"salt+1", baseMaster, append([]byte{0x23}, baseSalt[1:]...), baseContext},
		{"context+1", baseMaster, baseSalt, []byte("rgt-vault/test/sensitivit")}, // one byte shorter on purpose
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			dmBase, _ := Derive(baseMaster, baseSalt, baseContext, baseParams)
			dmCase, _ := Derive(c.master, c.salt, c.ctx, baseParams)
			if dmBase == dmCase {
				t.Errorf("Derive produced identical output when %s changed", c.name)
			}
		})
	}
}

// TestDerive_InputValidation covers the sentinel errors.
func TestDerive_InputValidation(t *testing.T) {
	goodMaster := bytes.Repeat([]byte{0x01}, 32)
	goodSalt := bytes.Repeat([]byte{0x02}, 16)
	goodContext := []byte("ok")
	goodParams := smallTestParams()

	tests := []struct {
		name    string
		master  []byte
		salt    []byte
		context []byte
		params  Params
		wantErr error
	}{
		{"short salt", goodMaster, []byte{0x01, 0x02, 0x03}, goodContext, goodParams, ErrInvalidSalt},
		{"empty context", goodMaster, goodSalt, nil, goodParams, ErrInvalidContext},
		{"zero memory", goodMaster, goodSalt, goodContext, Params{TimeCost: 2, Parallelism: 2}, ErrInvalidParams},
		{"zero time", goodMaster, goodSalt, goodContext, Params{MemoryCost: 65536, Parallelism: 2}, ErrInvalidParams},
		{"zero parallel", goodMaster, goodSalt, goodContext, Params{MemoryCost: 65536, TimeCost: 2}, ErrInvalidParams},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := Derive(tt.master, tt.salt, tt.context, tt.params)
			if err != tt.wantErr {
				t.Errorf("got %v, want %v", err, tt.wantErr)
			}
		})
	}
}

// TestSalt tests the convenience helper.
func TestSalt(t *testing.T) {
	s, err := Salt(16)
	if err != nil {
		t.Fatal(err)
	}
	if len(s) != 16 {
		t.Errorf("Salt(16) returned %d bytes, want 16", len(s))
	}
	// Two calls should not return the same bytes.
	s2, _ := Salt(16)
	if bytes.Equal(s, s2) {
		t.Error("Salt returned identical bytes on two consecutive calls (not random)")
	}
	// Under-min length should error.
	if _, err := Salt(4); err != ErrInvalidSalt {
		t.Errorf("Salt(4) err = %v, want %v", err, ErrInvalidSalt)
	}
}

// TestDefaultParams tests that the defaults match the Python defaults.
func TestDefaultParams(t *testing.T) {
	p := DefaultParams()
	if p.MemoryCost != DefaultMemoryCost {
		t.Errorf("DefaultParams().MemoryCost = %d, want %d", p.MemoryCost, DefaultMemoryCost)
	}
	if p.TimeCost != DefaultTimeCost {
		t.Errorf("DefaultParams().TimeCost = %d, want %d", p.TimeCost, DefaultTimeCost)
	}
	if p.Parallelism != DefaultParallelism {
		t.Errorf("DefaultParams().Parallelism = %d, want %d", p.Parallelism, DefaultParallelism)
	}
}

// TestConstantTimeEq sanity-checks the comparison helper.
func TestConstantTimeEq(t *testing.T) {
	a := []byte("hello world")
	b := []byte("hello world")
	c := []byte("hello worlD")
	if !ConstantTimeEq(a, b) {
		t.Error("ConstantTimeEq returned false for equal inputs")
	}
	if ConstantTimeEq(a, c) {
		t.Error("ConstantTimeEq returned true for differing inputs")
	}
	// Different lengths should also return false.
	if ConstantTimeEq(a, []byte("hello")) {
		t.Error("ConstantTimeEq returned true for different-length inputs")
	}
}

// smallTestParams returns a parameter set that runs in well under a second
// on any modern machine. Used by the round-trip tests so the suite stays
// fast. The cross-language parity test (TestVectorFromPython) uses the
// exact parameters from its vector, which happen to be the same.
//
// Note: this is intentionally NOT a public API. It is internal to the
// test file. Real callers should use DefaultParams() or a known-good
// set for their threat model.
func smallTestParams() Params {
	return Params{MemoryCost: 65536, TimeCost: 2, Parallelism: 2}
}
